server:
  port: 8080

api:
  prefix: /heoyy/api/v1/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    try-it-out-enabled: true
  api-docs:
    path: /api-docs
  packagesToScan: com.heoyy
  disable-swagger-default-url: true
  display-request-duration: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
